### ISSUE TITLE
Questions about FEARec-reproduce 

### ISSUE THREAD

**Issue by foureye** [yehjin-shin/BSARec#1]
I found the FEARec-reproduce is much higher than original paper。
（In dataset Beauty，original paper is 0.0597 HR@5  while in BSARec reproduce is 0.0706 HR@5）
I also found the FMLP-reproduce is little lower than other paper。
Is there any distinguish between hardware or environment set lead to the results？
Thank you ！

**Comment by Zhuohan007** [comment]
I also have the same question and hope the author can provide a response.

**Comment by yehjin-shin** [comment]
Hi,

I apologize for the late response. Before addressing your question, I'd like to clarify that in order to ensure a fair comparison between BSARec and other baselines, we aligned our experiments with _the same code base_. We conducted our experiments based on the [FMLP-Rec](https://github.com/Woeee/FMLP-Rec), and for other models, we made every effort to minimize changes to the official code. **_We have updated all the codes for baselines we used for our experiments._**

The answers to your question about reproducibility are as follows:

**1. FEARec** 
While we endeavored to use the original code with minimal modifications, the differences in code base could inevitably lead to performance differences. However, we identified one notable difference recently: the early stopping round. We applied a value of 10 for all models, including baselines, whereas FeaRec, according to their implementation, used 40. This discrepancy could potentially be a key to overall performance improvement.

**2. FMLP-Rec**
Despite conducting experiments with the same code base, we observed that it was challenging to reproduce the results. We are aware that differences in CUDA versions or the GPUs used could significantly affect the outcomes. While we suspect that these factors could play a role in the issue, the absence of detailed information from the authors prevents us from precisely identifying the cause of the performance differences.

I hope this response is helpful to you.

Thank you.

**Comment by foureye** [comment]
I  appreciate your reply and the updated codes for all the baselines.I have successfully reproduce the  result of the FEARec(In dataset Beauty,HR@5 is 0.0681).I also found the DuoRec-reproduce is 0.0673(Beauty HR@5).
The original result in DuoRec and FeaRec is run under the framework of recbole（a recommender system code base),i think this may be the main reason.
